# The following grid and coloring logic was generated by Gemini (Flash 2.0)
# on January 17, 2026, in response to a request for a 128x128 Tkinter grid.
# URL: https://gemini.google.com/

import random

from enum import Enum

from render import Renderer
from Characters import Hero, Enemy
from collections import deque

class Map:

    def __init__(self, Grid_num, cell_size, fill_percent:float):
        self.grid_num = Grid_num
        self.fill_percent = fill_percent
        self.hero = None  # to be updated 
        self.renderer = Renderer(Grid_num,cell_size,fill_percent)
        self.obstacle_coordinate_list = []
        self.is_map_full = False
        self.enemy_list = [] # to be updated
        self.goal_pos = None  # to be updated
        self.is_hero_at_goal = False
        self.is_game_over = False
        self.directions = [(-1,-1),(-1,1), (1,1),(1,-1),(0, 1),(-1, 0),(0, -1),(1, 0)]
        self._generate_goal()
        self._fill_map()       

    def generate_enemies(self,number_of_enemies):

        for i in range(number_of_enemies): 
            new_enemy = (Enemy(self.find_open_square()))
            self.renderer.color_cell(new_enemy.getCoordinate(),"red","triangle")
            self.enemy_list.append(new_enemy)

    def step_enemies(self):
        for enemy in self.enemy_list:
            if enemy.crashed == True:
                self.enemy_list.remove(enemy)
                continue
            elif self.hero:
                if self.hero.getCoordinate() == enemy.getCoordinate():
                    self.renderer.game_over_screen()
                    self.is_game_over = True
                    break
                self.determine_enemy_movement(enemy)
                if enemy.getCoordinate() in self.obstacle_coordinate_list:
                    enemy.become_obstacle()
                    self.append_new_obstacle(enemy.getCoordinate())

    def determine_enemy_movement(self,enemy:Enemy):
        """Finds the direction to move closest to the robot"""
        row, col = enemy.getCoordinate()
        best = None
        best_distance = 100000000.0

        for x, y in enemy.directions:
            new_row = row + x
            new_col = col + y

            if 0 <= new_row < self.grid_num and 0 <= new_col < self.grid_num:
                distance = abs(self.hero.getCoordinate()[0] - new_row) + abs(
                    self.hero.getCoordinate()[1] - new_col
                )
                if distance < best_distance:
                    best_distance = distance
                    best = (new_row, new_col)
        if best:
            enemy.move(best)
        else:
            return "error! no distance could be specified"
        
    def generate_hero(self):
        self.hero = Hero(self.find_open_square())

    def BFS(self):
        """ Preforms the BFS on the grid and plans a route"""
        self.hero.parent_dict[self.hero.getCoordinate()] = None
        while self.hero.queue:
            next_square = self.hero.queue.popleft()
            if next_square in self.hero.visited:
                raise Exception("seen this square, redunant checking")
            self.hero.visited.append(next_square)
            if next_square != self.goal_pos:
                for neighbor in self.determine_neighbors(next_square):
                    if neighbor not in self.hero.visited and neighbor not in self.hero.queue:
                        self.hero.queue.append(neighbor)
                        self.hero.parent_dict[neighbor] = next_square
                if len(self.hero.queue) == 0:
                    raise Exception("Hero unable to move from position")
            else:
                self.hero.queue = deque()
                self.hero.path_to_victory = self.reconstruct_path()
                self.hero.is_route_planned = True
            
    def determine_neighbors(self,coordinate):
        """ This finds and adds neighbor nodes into the queue"""
        neighbors = []
        for direction in self.hero.directions:
            new_coordinatex = coordinate[0] + direction[0]
            new_coordinatey = coordinate[1] + direction[1]
            new_coordinate = (new_coordinatex, new_coordinatey)
            if new_coordinate not in self.hero.visited and self.check_valid_cell(new_coordinate):
                neighbors.append(new_coordinate)
                
        return neighbors

    def check_valid_cell(self,coordinate):
        """
        This will be used to check if the hero has access to the square

        This is intended be a safety check to ensure smooth motion
        """
        row, col = coordinate
        retval = True

        # inside grid
        if row < 0 or row >= self.grid_num:
            retval = False
        if col < 0 or col >= self.grid_num:
            retval = False

        # not an obstacle
        if coordinate in self.obstacle_coordinate_list:
            retval = False

        return retval
    
    def reconstruct_path(self):
        """Determines the optimal path from the BFS algorithm"""
        reversed_path = []
        current_coordinate = self.goal_pos
        while current_coordinate is not None:
            reversed_path.append(current_coordinate)
            current_coordinate = self.hero.parent_dict[current_coordinate]
        if len(reversed_path) == 0:
            raise Exception("No path found in BFS")
        return reversed_path


    def detect_enemy_nearby(self,coordinate):
        """returns if there are upcoming dangerous robots nearby"""
        retval = False
        for direction in self.hero.enemy_radius:
            new_coordinatex = coordinate[0] + direction[0]
            new_coordinatey = coordinate[1] + direction[1]
            new_coordinate = (new_coordinatex, new_coordinatey)
            for enemy in self.enemy_list:
                if new_coordinate == enemy.getCoordinate():
                    retval = True
            # check for collisions:
        return retval
    
    def step_hero(self):
        if self.hero:
            if self.check_at_goal():
                self.is_hero_at_goal = True
            else:
                if self.hero.is_route_planned == False:
                    print("searching")
                    self.BFS()
                    print("completed search")
                coord_to_move = self.hero.path_to_victory.pop()
                if self.detect_enemy_nearby(coord_to_move):
                    self.hero.teleport_hero(self.find_open_square())
                else:
                    self.hero.move(coord_to_move)
                    #print("moving")
            

    def append_new_obstacle(self, coordinate):
        self.obstacle_coordinate_list.append(coordinate)
        self.renderer.color_cell(coordinate)

    # this function generates a random number associated with the shapes above
    def generate_random_tetromino(self):
        """This function generates a random number between 1 - 4 that is associated to a shape"""
        shape = random.choice([1, 2, 3, 4])
        return shape

    def generate_random_coord(self):
        """This function creates a random coordinate within the grid"""
        # 1. Create a list of all 16,384 possible (row, col) pairs
        all_coords = [
            (row, column)
            for row in range(self.grid_num)
            for column in range(self.grid_num)
        ]

        # 2. Pick unique pairs automatically
        sample = random.sample(all_coords, 1)
        return sample[0]

    def find_open_square(self):
        """This function uses a random coordinate and shape to determine if they would fit into the obstacle board's boundaries"""
        new_coordinate = self.generate_random_coord()
        if self.check_cell_occupied(new_coordinate):
            return self.find_open_square()
        else:
            return new_coordinate

    def check_cell_occupied(self, new_coordinate):
        retval = False
        for enemy in self.enemy_list:
            if enemy.getCoordinate() == new_coordinate:
                retval = True
        if (new_coordinate in self.obstacle_coordinate_list):
            retval = True
        elif (new_coordinate == self.goal_pos):
            retval = True
        elif (self.hero):
            if new_coordinate == self.hero.getCoordinate():
                retval = True
        return retval

    def _generate_goal(self):
        fail_counter = 0
        if isinstance(self.goal_pos, tuple):
            raise Exception("the goal has been defined before!")
        test_goal_pos = self.find_open_square()
        for direction in self.directions:
            goalx = test_goal_pos[0] + direction[0]
            goaly = test_goal_pos[1] + direction[1]
            trial_goal = (goalx, goaly)
            if self.check_cell_occupied(trial_goal):
                fail_counter = fail_counter + 1
                if fail_counter > 25:
                    raise Exception("Goal Could not be placed in valid location")
                self._generate_goal()
                break    
        self.goal_pos = test_goal_pos
        self.renderer.color_cell(
        self.goal_pos, "green"
                )
                
    def check_on_grid(self,coord):
        return (0 < coord[0] < self.grid_num and 0 < coord[1] < self.grid_num) 
     
    def generate_field_obstacle(self, shape, attempts=0):
        THREE_TALL = 1
        UPSIDEDOWN_L = 2
        TETRIS = 3
        HALF_PLUS = 4
        if attempts > 1000:
            print("over 1000 attempts trailed no place found")
            self.is_map_full = True
            return
        coordinate = self.find_open_square()
        #print(coordinate)
        x_cord = coordinate[0]
        y_cord = coordinate[1]
        coord_list = []
        if shape == THREE_TALL:  # boundary check for each shape
            if 0 < y_cord +1 < self.grid_num and 0 < y_cord - 1 < self.grid_num:
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                if (self.check_cell_occupied(above_cord) or self.check_cell_occupied(below_cord)
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [above_cord, below_cord]
                    coord_list.append((x_cord, y_cord))

        elif shape == UPSIDEDOWN_L:
            if x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128:
                left_cord = (x_cord - 1, y_cord - 1)
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                if (self.check_cell_occupied(left_cord) or self.check_cell_occupied(above_cord) or self.check_cell_occupied(below_cord)
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [left_cord, above_cord, below_cord]
                    coord_list.append((x_cord, y_cord))

        elif shape == TETRIS:
            if x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128:
                top_left_cord = (x_cord - 1, y_cord - 1)
                left_cord = (x_cord - 1, y_cord)
                below_cord = (x_cord, y_cord + 1)
                if (
                    left_cord in self.obstacle_coordinate_list
                    or top_left_cord in self.obstacle_coordinate_list
                    or below_cord in self.obstacle_coordinate_list
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [top_left_cord, left_cord, below_cord]
                    coord_list.append((x_cord, y_cord))

        elif shape == HALF_PLUS:
            if x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128:
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                left_cord = (x_cord - 1, y_cord)
                if (
                    above_cord in self.obstacle_coordinate_list
                    or below_cord in self.obstacle_coordinate_list
                    or left_cord in self.obstacle_coordinate_list
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [above_cord, below_cord, left_cord]
                    coord_list.append((x_cord, y_cord))

        for coordinate in coord_list:
            self.obstacle_coordinate_list.append(coordinate)
            self.renderer.color_cell(coordinate)
        
    def _fill_map(self):
        while(not self.is_map_full and len(self.obstacle_coordinate_list) < self.grid_num*self.grid_num*self.fill_percent):
            self.generate_field_obstacle(self.generate_random_tetromino())
        #debug test 
        #print(f" length of obstacle list {len(self.obstacle_coordinate_list)}. the number of cells: {self.grid_num*self.grid_num}.")
        
    

    def _remove_enities(self):
        # removes all entities
            for enemy in self.enemy_list:
                if not enemy.crashed:
                    self.renderer.color_cell(enemy.getCoordinate(),"white")
            if self.hero:
                self.renderer.color_cell(self.hero.getCoordinate(),"white")

    def update_characters(self):
        """
        Updates enemy and hero position and updates the current list

        Should run every loop call to ensure proper display

        """
        if not self.is_game_over:
            self._remove_enities()
            self.step_hero()
            if self.is_hero_at_goal == False:
                self.step_enemies()
            self.renderer.color_cell(self.goal_pos,"green")
            for enemy in self.enemy_list:
                    self.renderer.color_cell(enemy.getCoordinate(), "red", "triangle")
            if self.hero:
                self.renderer.color_cell(self.hero.getCoordinate(), "black", "circle")
        

    def check_game_over(self):
        retval = False
        for enemy in self.enemy_list:
            if self.hero.getCoordinate() == enemy.getCoordinate():
                retval = True
        return retval
    
    def check_at_goal(self):
        """
        Checks if the hero's current position matches the goal
        """
        if self.hero.getCoordinate() == self.goal_pos:
            #print("reached goal")
            return True
        else:
            return False

   
if __name__ == "__main__":
    pass
    test = Map(30,40,0)
    test.hero = Hero((1,1))
    test.goal_pos = (1,15)
    for i in range(50):
        test.update_characters()
    test.renderer.Open_map()
    # test.generate_hero()
    # test.step_hero()
    # flag = True
    # test.step_enemies()
    # test.renderer.root.after(300, main)
    # test.renderer.Open_map()