# The following grid and coloring logic was generated by Gemini (Flash 2.0)
# on January 17, 2026, in response to a request for a 128x128 Tkinter grid.
# URL: https://gemini.google.com/

import tkinter as tk

import random

from enum import Enum

class Map:

    def __init__(self,Grid_num,cell_size,fill_percent):
        self.grid_num = Grid_num
        self.cell_size = cell_size
        self.fill_percent = fill_percent
        self.obstacle_coordinate_list = []
        self.root = tk.Tk()
        self.root.title("The Hero's Jounery")

        # Create a canvas large enough for 128 cells
        self.canvas_dim = self.grid_num * self.cell_size
        self.canvas = tk.Canvas(self.root, width=self.canvas_dim, height=self.canvas_dim, bg="white")
        self.canvas.pack(padx=10, pady=10)

    def draw_128_grid(self,canvas): 
        """This function creates a canvas of size 128 x 128"""
        max_dim = self.grid_num * self.cell_size
        # Draw Vertical Lines
        for x in range(0, max_dim + self.cell_size, self.cell_size):
            canvas.create_line(x, 0, x, max_dim, fill="lightgray")
        # Draw Horizontal Lines
        for y in range(0, max_dim + self.cell_size, self.cell_size):
            canvas.create_line(0, y, max_dim, y, fill="lightgray")

    #this function generates a random number associated with the shapes above
    def generate_random_tetromino(self):
        """This function generates a random number between 1 - 4 that is associated to a shape"""
        shape = random.choice([1,2,3,4])
        return shape


    def generate_random_coord(self):
        """This function creates a random coordinate within the grid"""
        # 1. Create a list of all 16,384 possible (row, col) pairs
        all_coords = [(row, column) for row in range(self.grid_num) for column in range(self.grid_num)]

        # 2. Pick unique pairs automatically
        return random.sample(all_coords, 1)

    def determine_open_square(self):
        """This function uses a random coordinate and shape to determine if they would fit into the obstacle board's boundaries"""
        new_coordinate = self.generate_random_coord()
        if(new_coordinate in self.obstacle_coordinate_list):
            self.determine_open_square()
        else:
            return new_coordinate
    
    def generate_field_obstacle(self, shape, attempts):
        THREE_TALL = 1
        UPSIDEDOWN_L = 2
        TETRIS = 3
        HALF_PLUS = 4
        if attempts > 1000:
            return True
        coordinate = self.determine_open_square()
        x_cord = coordinate[0][0]
        y_cord = coordinate[0][1]
        coord_list = []
        if(shape == THREE_TALL): #boundary check for each shape
            if(y_cord + 1 <= 128 and y_cord - 1 >= 0):
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                if(above_cord in self.obstacle_coordinate_list or below_cord in self.obstacle_coordinate_list):
                    self.generate_field_obstacle(shape, attempts+1)
                else:
                    coord_list = [above_cord, below_cord]
                    coord_list.append((x_cord,y_cord))          

        elif(shape == UPSIDEDOWN_L): 
            if(x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128):
                left_cord = (x_cord - 1 , y_cord - 1)
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                if(left_cord in self.obstacle_coordinate_list or above_cord in self.obstacle_coordinate_list or below_cord in self.obstacle_coordinate_list):
                    self.generate_field_obstacle(shape, attempts+1)
                else:
                    coord_list = [left_cord,above_cord,below_cord]
                    coord_list.append((x_cord,y_cord))

        elif(shape == TETRIS):
            if(x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128):
                top_left_cord = (x_cord - 1 , y_cord - 1)
                left_cord = (x_cord - 1, y_cord )
                below_cord = (x_cord , y_cord + 1)
                if(left_cord in self.obstacle_coordinate_list or top_left_cord in self.obstacle_coordinate_list or below_cord in self.obstacle_coordinate_list):
                    self.generate_field_obstacle(shape, attempts+1)
                else:
                    coord_list = [top_left_cord,left_cord,below_cord]
                    coord_list.append((x_cord,y_cord))

        elif(shape == HALF_PLUS):
            if(x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128):
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                left_cord = (x_cord - 1, y_cord )
                if(above_cord in self.obstacle_coordinate_list or below_cord in self.obstacle_coordinate_list or left_cord in self.obstacle_coordinate_list):
                    self.generate_field_obstacle(shape, attempts+1)
                else:
                    coord_list = [above_cord, below_cord, left_cord]
                    coord_list.append((x_cord,y_cord))

        for coordinate in coord_list:
                self.obstacle_coordinate_list.append(coordinate)
                self.color_cell(self.canvas,coordinate[1],coordinate[0])
        return False

    def color_cell(self, canvas, row, col, color="black"):
        """This function colors the cells of the canvas"""
        # Ensure coordinates are within 128x128 bounds
        if 0 <= row < self.grid_num and 0 <= col < self.grid_num:
            x1 = col * self.cell_size
            y1 = row * self.cell_size
            x2 = x1 + self.cell_size
            y2 = y1 + self.cell_size
            canvas.create_rectangle(x1, y1, x2, y2, fill=color, outline="lightgray")
    
    def generate_hero():
        pass

    def generate_enemies():
        pass

    def move_enemies():
        pass

    def generate_goal():
        pass

    def teleport_hero():
        pass

    def Fill_map(self):
        # Draw the 128x128 lines
        self.draw_128_grid(self.canvas)
        while len(self.obstacle_coordinate_list) < self.grid_num*self.grid_num*self.fill_percent:
            if self.generate_field_obstacle(self.generate_random_tetromino(), 0):
                print("too many attempts")
                break
    def Open_map(self):
        self.root.mainloop()

    
map1 = Map(64,20,0.2)
map1.Fill_map()
map1.Open_map()








    

