# The following grid and coloring logic was generated by Gemini (Flash 2.0)
# on January 17, 2026, in response to a request for a 128x128 Tkinter grid.
# URL: https://gemini.google.com/

import random

from enum import Enum

from render import Renderer
from collections import deque

class Map:

    def __init__(self, Grid_num, cell_size, fill_percent:float):
        #each cell is 3 meters by 3 meters in real distance
        self.grid_num = Grid_num
        self.fill_percent = fill_percent
        self.hero = None  # to be updated 
        self.renderer = Renderer(Grid_num,cell_size,fill_percent)
        self.obstacle_coordinate_list = []
        self.is_map_full = False
        self.enemy_list = [] # to be updated
        self.goal_pos = None  # to be updated
        self.is_hero_at_goal = False
        self.is_game_over = False
        self.directions = [(-1,-1),(-1,1), (1,1),(1,-1),(0, 1),(-1, 0),(0, -1),(1, 0)]
        self._generate_goal()
        self._fill_map()       

    
    def check_valid_cell(self,coordinate):
        """
        This will be used to check if the hero has access to the square

        This is intended be a safety check to ensure smooth motion
        """
        row, col = coordinate
        retval = True

        # inside grid
        if row < 0 or row >= self.grid_num:
            retval = False
        if col < 0 or col >= self.grid_num:
            retval = False

        # not an obstacle
        if coordinate in self.obstacle_coordinate_list:
            retval = False

        return retval
    
    def reconstruct_path(self):
        """Determines the optimal path from the BFS algorithm"""
        reversed_path = []
        current_coordinate = self.goal_pos
        while current_coordinate is not None:
            reversed_path.append(current_coordinate)
            current_coordinate = self.hero.parent_dict[current_coordinate]
        if len(reversed_path) == 0:
            raise Exception("No path found in BFS")
        return reversed_path
            

    def append_new_obstacle(self, coordinate):
        self.obstacle_coordinate_list.append(coordinate)
        self.renderer.color_cell(coordinate)

    # this function generates a random number associated with the shapes above
    def generate_random_tetromino(self):
        """This function generates a random number between 1 - 4 that is associated to a shape"""
        shape = random.choice([1, 2, 3, 4])
        return shape

    def generate_random_coord(self):
        """This function creates a random coordinate within the grid"""
        # 1. Create a list of all 16,384 possible (row, col) pairs
        all_coords = [
            (row, column)
            for row in range(self.grid_num)
            for column in range(self.grid_num)
        ]

        # 2. Pick unique pairs automatically
        sample = random.sample(all_coords, 1)
        return sample[0]

    def find_open_square(self):
        """This function uses a random coordinate and shape to determine if they would fit into the obstacle board's boundaries"""
        new_coordinate = self.generate_random_coord()
        if self.check_cell_occupied(new_coordinate):
            return self.find_open_square()
        else:
            return new_coordinate

    def check_cell_occupied(self, new_coordinate):
        retval = False
        if (new_coordinate in self.obstacle_coordinate_list):
            retval = True
        elif (new_coordinate == self.goal_pos):
            retval = True


    def _generate_goal(self):
        fail_counter = 0
        if isinstance(self.goal_pos, tuple):
            raise Exception("the goal has been defined before!")
        test_goal_pos = self.find_open_square()
        for direction in self.directions:
            goalx = test_goal_pos[0] + direction[0]
            goaly = test_goal_pos[1] + direction[1]
            trial_goal = (goalx, goaly)
            if self.check_cell_occupied(trial_goal):
                fail_counter = fail_counter + 1
                if fail_counter > 25:
                    raise Exception("Goal Could not be placed in valid location")
                self._generate_goal()
                break    
        self.goal_pos = test_goal_pos
        self.renderer.color_cell(
        self.goal_pos, "green"
                )
                
    def check_on_grid(self,coord):
        return (0 < coord[0] < self.grid_num and 0 < coord[1] < self.grid_num) 
     
    def generate_field_obstacle(self, shape, attempts=0):
        THREE_TALL = 1
        UPSIDEDOWN_L = 2
        TETRIS = 3
        HALF_PLUS = 4
        if attempts > 1000:
            print("over 1000 attempts trailed no place found")
            self.is_map_full = True
            return
        coordinate = self.find_open_square()
        #print(coordinate)
        x_cord = coordinate[0]
        y_cord = coordinate[1]
        coord_list = []
        if shape == THREE_TALL:  # boundary check for each shape
            if 0 < y_cord +1 < self.grid_num and 0 < y_cord - 1 < self.grid_num:
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                if (self.check_cell_occupied(above_cord) or self.check_cell_occupied(below_cord)
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [above_cord, below_cord]
                    coord_list.append((x_cord, y_cord))

        elif shape == UPSIDEDOWN_L:
            if x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128:
                left_cord = (x_cord - 1, y_cord - 1)
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                if (self.check_cell_occupied(left_cord) or self.check_cell_occupied(above_cord) or self.check_cell_occupied(below_cord)
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [left_cord, above_cord, below_cord]
                    coord_list.append((x_cord, y_cord))

        elif shape == TETRIS:
            if x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128:
                top_left_cord = (x_cord - 1, y_cord - 1)
                left_cord = (x_cord - 1, y_cord)
                below_cord = (x_cord, y_cord + 1)
                if (
                    left_cord in self.obstacle_coordinate_list
                    or top_left_cord in self.obstacle_coordinate_list
                    or below_cord in self.obstacle_coordinate_list
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [top_left_cord, left_cord, below_cord]
                    coord_list.append((x_cord, y_cord))

        elif shape == HALF_PLUS:
            if x_cord - 1 >= 0 and y_cord - 1 >= 0 and y_cord + 1 <= 128:
                above_cord = (x_cord, y_cord - 1)
                below_cord = (x_cord, y_cord + 1)
                left_cord = (x_cord - 1, y_cord)
                if (
                    above_cord in self.obstacle_coordinate_list
                    or below_cord in self.obstacle_coordinate_list
                    or left_cord in self.obstacle_coordinate_list
                ):
                    self.generate_field_obstacle(shape, attempts + 1)
                else:
                    coord_list = [above_cord, below_cord, left_cord]
                    coord_list.append((x_cord, y_cord))

        for coordinate in coord_list:
            self.obstacle_coordinate_list.append(coordinate)
            self.renderer.color_cell(coordinate)
        
    def _fill_map(self):
        while(not self.is_map_full and len(self.obstacle_coordinate_list) < self.grid_num*self.grid_num*self.fill_percent):
            self.generate_field_obstacle(self.generate_random_tetromino())
        #debug test 
        #print(f" length of obstacle list {len(self.obstacle_coordinate_list)}. the number of cells: {self.grid_num*self.grid_num}.")
        
    

    def _remove_enities(self):
        # removes all entities
        pass 

    def update_characters(self):
        """
        Updates enemy and hero position and updates the current list

        Should run every loop call to ensure proper display

        """
        pass
        

   
if __name__ == "__main__":
    pass
    