# The following grid and coloring logic was generated by Gemini (Flash 2.0)
# on January 17, 2026, in response to a request for a 128x128 Tkinter grid.
# URL: https://gemini.google.com/

import random

from enum import Enum

from collections import deque
from typing import Optional


class Map:

    def __init__(self, Grid_num, cell_size, fill_percent: float):
        # each cell is 3 meters by 3 meters in real distance
        self.grid_num = Grid_num
        self.cell_size = cell_size
        self.fill_percent = fill_percent
        # self.renderer = Renderer(Grid_num, cell_size, fill_percent)
        self.obstacle_coordinate_list = []
        self.is_map_full = False
        self.goal_pos: Optional[tuple[float, float]] = None  # to be updated
        self._fill_map()
        self._generate_goal()

    def check_valid_cell(self, coordinate):
        """
        This will be used to check if the hero has access to the square

        This is intended be a safety check to ensure smooth motion
        """
        row, col = coordinate
        # Ensure we stay within the discrete grid bounds (0-11 for a 12x12)
        if not (0 <= row < self.grid_num and 0 <= col < self.grid_num):
            return False
        if (row, col) in self.obstacle_coordinate_list:
            return False
        return True

    def append_new_obstacle(self, coordinate):
        self.obstacle_coordinate_list.append(coordinate)
        # self.renderer.color_cell(coordinate)

    # this function generates a random number associated with the shapes above
    def generate_random_tetromino(self):
        """This function generates a random number between 1 - 4 that is associated to a shape"""
        shape = random.choice([1, 2, 3, 4])
        return shape

    def generate_random_coord(self):
        """This function creates a random coordinate within the grid"""
        # 1. Create a list of all 16,384 possible (row, col) pairs
        all_coords = [
            (row, column)
            for row in range(self.grid_num)
            for column in range(self.grid_num)
        ]

        # 2. Pick unique pairs automatically
        sample = random.sample(all_coords, 1)
        return sample[0]

    def find_open_square(self):
        """This function uses a random coordinate and shape to determine if they would fit into the obstacle board's boundaries"""
        new_coordinate = self.generate_random_coord()
        if self.check_cell_occupied(new_coordinate):
            return self.find_open_square()
        else:
            return new_coordinate

    def check_cell_occupied(self, new_coordinate):
        """CRITICAL: Added 'return' statements here"""
        if new_coordinate in self.obstacle_coordinate_list or new_coordinate in [(0, 0),(1,0),(0,1),(1,1)]:
            return True
        if self.goal_pos:
            # Check if this grid cell contains the goal
            goal_grid = (
                int(self.goal_pos[0] / self.cell_size),
                int(self.goal_pos[1] / self.cell_size),
            )
            if new_coordinate == goal_grid:
                return True
        return False  # Ensure we return False if free

    def _generate_goal(self):
        """Generates a goal in a free cell and converts to world meters"""
        # 1. Find a random grid coordinate that isn't an obstacle
        all_coords = [
            (r, c) for r in range(self.grid_num) for c in range(self.grid_num)
        ]
        free_coords = [c for c in all_coords if c not in self.obstacle_coordinate_list]

        if not free_coords:
            self.goal_pos = (
                self.grid_num * self.cell_size / 2,
                self.grid_num * self.cell_size / 2,
            )
            return

        target_cell = random.choice(free_coords)

        # 2. Convert grid index to real-world meters
        # Center of cell (row, col) is (row * 3 + 1.5, col * 3 + 1.5)
        self.goal_pos = (
            (target_cell[0] * self.cell_size) + (self.cell_size / 2),
            (target_cell[1] * self.cell_size) + (self.cell_size / 2),
        )

    def check_on_grid(self, coord):
        return 0 < coord[0] < self.grid_num and 0 < coord[1] < self.grid_num

    def generate_field_obstacle(self, shape, attempts=0):
        if attempts > 100:  # Reduced for smaller grids
            self.is_map_full = True
            return

        # Pick a random starting point for the tetromino
        x, y = random.randint(0, self.grid_num - 1), random.randint(
            0, self.grid_num - 1
        )

        # Logic for shapes (using grid indices)
        # We replace the hardcoded '128' with self.grid_num
        potential_coords = []

        if shape == 1:  # Three Tall
            potential_coords = [(x, y), (x, y - 1), (x, y + 1)]
        elif shape == 2:  # L-Shape
            potential_coords = [(x, y), (x - 1, y - 1), (x, y - 1), (x, y + 1)]
        elif shape == 3:  # Z-Shape
            potential_coords = [(x, y), (x - 1, y - 1), (x - 1, y), (x, y + 1)]
        elif shape == 4:  # T-Shape
            potential_coords = [(x, y), (x, y - 1), (x, y + 1), (x - 1, y)]

        # Validate all pieces of the shape fit and are not overlapping
        valid = True
        for pc in potential_coords:
            if not (0 <= pc[0] < self.grid_num and 0 <= pc[1] < self.grid_num):
                valid = False
                break
            if self.check_cell_occupied(pc):
                valid = False
                break

        if valid:
            self.obstacle_coordinate_list.extend(potential_coords)
        else:
            self.generate_field_obstacle(shape, attempts + 1)

    def _fill_map(self):
        while (
            not self.is_map_full
            and len(self.obstacle_coordinate_list)
            < self.grid_num * self.grid_num * self.fill_percent
        ):
            self.generate_field_obstacle(self.generate_random_tetromino())


if __name__ == "__main__":
    pass
