# The following grid and coloring logic was generated by Gemini (Flash 2.0)
# on January 17, 2026, in response to a request for a 128x128 Tkinter grid.
# URL: https://gemini.google.com/

import random

from enum import Enum, auto
from queue import Queue

from collections import deque
from typing import Optional

from shapely import Point, box
import time
import math


class Status(Enum):
    INTACT = auto()
    BURNING = auto()
    EXTINGUISHED = auto()
    BURNED = auto()

RED = "\033[31m"
RESET = "\033[0m"

class Map:

    def __init__(self, Grid_num, cell_size, fill_percent: float, wumpus, firetruck, firetruck_pose: Optional[tuple[float]] = None, wumpus_pose:Optional[tuple[float]] = None):
        # each cell is 5 meters by 5 meters in real distance
        self.grid_num = Grid_num
        self.cell_size = cell_size
        self.fill_percent = fill_percent
        self.obstacle_coordinate_dict = (
            {} # dict of dicts { coordinate: {'status': Status.status, 'burn_time': none, 'extinguish_time' : None}}
        )  
        self.obstacle_set = set()  # all coordinates for quicker collisions and lookups.
        self.active_fires = set()
        self.is_map_full = False
        self.firetruck_goal: Optional[tuple[float, float, float]] = None  # to be updated
        self.sim_time = 0.0
        # add firetruck location and wumpus location for generate safe map
        self.firetruck_pose = firetruck_pose
        self.wumpus_pose = wumpus_pose
        self.firetruck = firetruck
        self.wumpus = wumpus

        try:
            self.generate_safe_map(firetruck_pose,wumpus_pose,buffer_radius=6)
        except Exception:
            print(f'Firetruck has pose {firetruck_pose}, wumpus has pose {wumpus_pose} \n cannot generate obstacles!')
        

    def main(self):
        # repeats for every 0.1s of sim time
        self.update_sim_time()
        self.check_time_events()
        if self.sim_time > 3600:
            return "Done"
        
        # wumpus_path = self.wumpus.plan()
        # firetruck_path = self.firetruck.plan()

        #need to refine logic for this here

            




    def update_sim_time(self):
        self.sim_time += 0.1

        if self.sim_time > 3600:
            print(
                f"WARNING TIME IS ABOVE THE 3600 SECOND THRESHOLD!!! END SEQUENCE NOW"
            )

    def set_burn_time(self, coordinate):
        # open a thread which just puts the time differential of the when the timers started and the current elapsed time
        # obstacles burning will be put into a dictionary of {(coordinate pair): (start_burn_time, start_extinguished_time)}
        # extinguished time will be set to NONE until firetruck has approached the block, changing it to current sim time.
        # this function will continuously mututate the currentElapsedtime part of the tuple for other logic checkers to use.
        burn_time = self.obstacle_coordinate_dict[coordinate]["burn_time"]
        if burn_time is None:
            self.obstacle_coordinate_dict[coordinate]["burn_time"] = self.sim_time
        else:
            print("Already has burn time!")

    def check_time_events(self):
        """
        Called every tick. Advances fire state based on elapsed burn time.
        """

        for coordinate, dictionary in list(self.obstacle_coordinate_dict.items()):
            burn_time = dictionary["burn_time"]
            if burn_time is None:
                continue
    
            elapsed = self.sim_time - burn_time
    
            if elapsed > 30:
                # Cell has burned out completely
                print(f"Obstacle at {coordinate} has burned out at t={self.sim_time:.1f}s")
                self.set_status_on_obstacles([coordinate], Status.BURNED)  # FIX: wrap in list
                # self._delete_obstacle(coordinate)
    
            elif elapsed > 10:
                # Fire has been burning long enough to spread to neighbours
                nearby_obstacles = self.find_burnable_obstacles(coordinate)  # FIX: pass coordinate
                if nearby_obstacles:
                    self.set_status_on_obstacles(nearby_obstacles, Status.BURNING)
    

    def find_burnable_obstacles(self, coordinate, radius_cells=6):
        center_x, center_y = coordinate
        found_obstacles = []

        # Iterate through the grid bounds
        for x in range(center_x - radius_cells, center_x + radius_cells + 1):
            for y in range(center_y - radius_cells, center_y + radius_cells + 1):

                # Use Euclidean distance to keep it a true 30m circle
                if (x - center_x) ** 2 + (y - center_y) ** 2 <= radius_cells**2:
                    if (x, y) in self.obstacle_set:
                        found_obstacles.append((x, y))

        return found_obstacles

    def set_status_on_obstacles(
        self, coordinates: list[tuple[float, float]], status: Status
    ):  
        # obstacles_to_change_status = self.find_neighbor_obstacles(coordinate=coordinate)
        if not isinstance(coordinates,list):
            if len(coordinates) == 2:
                coordinates = (coordinates[0],coordinates[1],0.0)
            coordinates = [coordinates]
        for coord in coordinates:
            currStatus = self.obstacle_coordinate_dict[coord]["status"]
            if currStatus == status:
                continue
            match currStatus:
                case Status.EXTINGUISHED | Status.BURNED:
                    continue
                case Status.INTACT:
                    self.obstacle_coordinate_dict[coord]["status"] = status
                    if status == Status.BURNING:
                        self.set_burn_time(coord)
                        self.active_fires.add(coord)
                case Status.BURNING:
                        self.obstacle_coordinate_dict[coord]["status"] = status
                        self.obstacle_coordinate_dict[coord]['burn_time'] = None
                        self.obstacle_coordinate_dict[coord]['extinguish_time'] = None
                        try: 
                            self.active_fires.remove(coord)
                        except KeyError:
                            print('prematurely set to extinguished/burning without being in active fire list')
                

    def update_goal(self, goal: tuple[float, float, float]):
        self.firetruck_goal = goal

    def find_firetruck_goal(self):
        """
        Returns the goal pose (x_m, y_m, theta_deg) for the firetruck.
    
        Priority:
        1. Nearest BURNING obstacle (stop 7m short so truck parks beside it)
        2. Wumpus position (no active fires — go intercept the wumpus)
    
        FIX: convert grid cell (row, col) → world metres using cell_size.
        Original code used raw grid indices as metres, producing goals that
        were ~cell_size times too close to the origin.
        """
        if len(self.active_fires) == 0:
            try:
                wp = self.wumpus_pose
                # wumpus_pose is stored in world metres already
                return (float(wp[0]), float(wp[1]))
            except Exception as e:
                print(f"Cannot get Wumpus pose! Error {e}")
                return (100.0, 100.0, 0.0)
    
        fx, fy, ftheta = self.firetruck_pose
        closest_dist = float('inf')
        closest_coord = None
    
        for coordinate_pair in self.active_fires:
            # FIX: convert grid cell centre to world metres
            fire_world_x = coordinate_pair[0] * self.cell_size + self.cell_size / 2.0
            fire_world_y = coordinate_pair[1] * self.cell_size + self.cell_size / 2.0
            distance = math.dist((fx, fy), (fire_world_x, fire_world_y))
            if distance < closest_dist:
                closest_dist = distance
                closest_coord = coordinate_pair
    
        # Convert the chosen cell to world metres
        target_x = closest_coord[0] * self.cell_size + self.cell_size / 2.0
        target_y = closest_coord[1] * self.cell_size + self.cell_size / 2.0
    
        dx = target_x - fx
        dy = target_y - fy
        distance = math.sqrt(dx ** 2 + dy ** 2)
        angle_to_fire = math.degrees(math.atan2(dy, dx)) % 360
        stop_distance = self.cell_size * 1.5   # park 1.5 cells short of the fire
    
        if distance <= stop_distance:
            # Already close enough — face the fire and stay put
            return (fx, fy, angle_to_fire)
    
        ratio = (distance - stop_distance) / distance
        goal_x = fx + dx * ratio
        goal_y = fy + dy * ratio
    
        # Safety: reject goal if it lands inside an obstacle cell
        goal_cell = (int(goal_x / self.cell_size), int(goal_y / self.cell_size))
        if goal_cell in self.obstacle_set:
            return 'ERROR CANT GO HERE'
    
        return (goal_x, goal_y, angle_to_fire)
    
    def get_status(self,coordinate):
        return self.obstacle_coordinate_dict[coordinate]['status']
        
    def generate_safe_map(self, start_pos, wumpus_pos, buffer_radius=6.0):
        """
        Generates obstacles while ensuring a continuous clearance zone.
        """

        safe_firetruck_start = Point(start_pos[0], start_pos[1]).buffer(buffer_radius)
        safe_wumpus_start = Point(wumpus_pos[0], wumpus_pos[1]).buffer(buffer_radius)

        final_obstacles = []
        cell_size = 5

        candidate_coordinates = self._fill_map()
        # Logic to pick random row/cols
        for row, col in candidate_coordinates:
            # Create the physical box for this obstacle
            obs_box = box(
                row * cell_size,
                col * cell_size,
                (row + 1) * cell_size,
                (col + 1) * cell_size,
            )

            # CONTINUOUS CHECK:
            # If the box overlaps the 3m circle around start or goal, skip it.
            if obs_box.intersects(safe_firetruck_start) or obs_box.intersects(safe_wumpus_start):
                continue

            final_obstacles.append((row, col))

        for obstacle in final_obstacles:
            self._append_new_obstacle(obstacle)

    def check_valid_cell(self, coordinate):
        """
        This will be used to check if the hero has access to the square

        This is intended be a safety check to ensure smooth motion
        """
        row, col = coordinate
        # Ensure we stay within the discrete grid bounds (0-11 for a 12x12)
        if not (0 <= row < self.grid_num and 0 <= col < self.grid_num):
            return False
        if (row, col) in self.obstacle_set:
            return False
        return True

    def find_neighbor_obstacles(self, coordinate: tuple[float, float]):
        DIRECTIONS = [
            (1, 0),
            (1, 1),
            (0, 1),
            (0, -1),
            (-1, -1),
            (1, -1),
            (-1, 1),
            (-1, 0),
        ]
        all_connected_obstacles = []
        queue = Queue()
        queue.put(coordinate)
        while not queue.empty:
            currCoord = queue.get()
            for direction in DIRECTIONS:
                x, y = currCoord
                dx, dy = direction
                new_coord = (x + dx, y + dy)
                if new_coord in self.obstacle_set:
                    all_connected_obstacles.append(new_coord)
                    queue.put(new_coord)

        return all_connected_obstacles

    def _append_new_obstacle(self, coordinate):
        self.obstacle_coordinate_dict[coordinate] = {
            "status": Status.INTACT,
            "burn_time": None,
            "extinguish_time": None,
        }
        self.obstacle_set.add(coordinate)

    def _delete_obstacle(self, coordinate):
        del self.obstacle_coordinate_dict[coordinate]
        self.obstacle_set.remove(coordinate)

    # this function generates a random number associated with the shapes above
    def generate_random_tetromino(self):
        """This function generates a random number between 1 - 4 that is associated to a shape"""
        shape = random.choice([1, 2, 3, 4])
        return shape

    def generate_random_coord(self):
        """This function creates a random coordinate within the grid"""
        # 1. Create a list of all 16,384 possible (row, col) pairs
        local_random = random.Random()
        all_coords = [
            (row, column)
            for row in range(self.grid_num)
            for column in range(self.grid_num)
        ]

        # 2. Pick unique pairs automatically
        sample = local_random.sample(all_coords, 1)
        return sample[0]

    def find_open_square(self):
        """This function uses a random coordinate and shape to determine if they would fit into the obstacle board's boundaries"""
        new_coordinate = self.generate_random_coord()
        if self.check_cell_occupied(new_coordinate):
            return self.find_open_square()
        else:
            return new_coordinate

    def check_cell_occupied(self, new_coordinate):
        if new_coordinate in self.obstacle_set or new_coordinate in [
            (0, 0),
            (1, 0),
            (0, 1),
            (1, 1),
        ]:
            return True
        if self.firetruck_goal:
            # Check if this grid cell contains the goal
            goal_grid = (
                int(self.firetruck_goal[0] / self.cell_size),
                int(self.firetruck_goal[1] / self.cell_size),
            )
            if new_coordinate == goal_grid:
                return True
        return False  # Ensure we return False if free

    def _generate_goal(self):
        """Generates a goal in a free cell and converts to world meters"""
        # 1. Find a random grid coordinate that isn't an obstacle
        all_coords = [
            (r, c) for r in range(self.grid_num) for c in range(self.grid_num)
        ]
        free_coords = [c for c in all_coords if c not in self.obstacle_set]

        if not free_coords:
            self.firetruck_goal = (
                self.grid_num * self.cell_size / 2,
                self.grid_num * self.cell_size / 2,
            )
            return

        target_cell = random.choice(free_coords)

        # 2. Convert grid index to real-world meters
        self.firetruck_goal = (
            (target_cell[0] * self.cell_size) + (self.cell_size / 2),
            (target_cell[1] * self.cell_size) + (self.cell_size / 2),
        )

    def check_on_grid(self, coord):
        return 0 < coord[0] < self.grid_num and 0 < coord[1] < self.grid_num

    def generate_field_obstacle(self, shape, attempts=0):
        if attempts > 100:  # Reduced for smaller grids
            self.is_map_full = True
            return None

        # Pick a random starting point for the tetromino
        x, y = random.randint(0, self.grid_num - 1), random.randint(
            0, self.grid_num - 1
        )

        # Logic for shapes (using grid indices)
        # We replace the hardcoded '128' with self.grid_num
        potential_coords = []

        if shape == 1:  # Three Tall
            potential_coords = [(x, y), (x, y - 1), (x, y + 1)]
        elif shape == 2:  # L-Shape
            potential_coords = [(x, y), (x - 1, y - 1), (x, y - 1), (x, y + 1)]
        elif shape == 3:  # Z-Shape
            potential_coords = [(x, y), (x - 1, y - 1), (x - 1, y), (x, y + 1)]
        elif shape == 4:  # T-Shape
            potential_coords = [(x, y), (x, y - 1), (x, y + 1), (x - 1, y)]

        # Validate all pieces of the shape fit and are not overlapping
        valid = True
        for pc in potential_coords:
            if not (0 <= pc[0] < self.grid_num and 0 <= pc[1] < self.grid_num):
                valid = False
                break
            if self.check_cell_occupied(pc):
                valid = False
                break

        if valid:
            return potential_coords
        else:
            return self.generate_field_obstacle(shape, attempts + 1)

    def _fill_map(self):
        obstacle_list = []
        while (
            not self.is_map_full
            and len(obstacle_list) < self.grid_num * self.grid_num * self.fill_percent
        ):
            obstacles = self.generate_field_obstacle(self.generate_random_tetromino())
            if obstacles:
                obstacle_list.extend(obstacles)

        return obstacle_list
