# The following grid and coloring logic was generated by Gemini (Flash 2.0)
# on January 17, 2026, in response to a request for a 128x128 Tkinter grid.
# URL: https://gemini.google.com/

import random

from enum import Enum, auto
from queue import Queue

from collections import deque
from typing import Optional

from shapely import Point,box

class Status(Enum):
    INTACT = auto()
    BURNING = auto()
    EXTINGUISHED = auto()
    BURNED = auto()

class Map:

    def __init__(self, Grid_num, cell_size, fill_percent: float):
        # each cell is 5 meters by 5 meters in real distance
        self.grid_num = Grid_num
        self.cell_size = cell_size
        self.fill_percent = fill_percent
        self.obstacle_coordinate_dict = {} #(coord) : state (intact, burning, extinguished, burned)
        self.obstacle_time_dict = {} # (coord pair) : start_time 
        self.is_map_full = False
        self.goal_pos: Optional[tuple[float, float, float]] = None  # to be updated
        
    def update_obstacle_time(self):
        #open a thread which just puts the time differential of the when the timers started and the current elapsed time
        #obstacles burning will be put into a dictionary of {(coordinate pair): (start_burn_time, start_extinguished_time)}
        #extinguished time will be set to NONE until firetruck has approached the block, changing it to current sim time.
        #this function will continuously mututate the currentElapsedtime part of the tuple for other logic checkers to use. 
        pass

    def check_all_timers(self):
        #uses current sim time to compare to the obstacle's start burn time and extinguished time
        pass

    def update_goal(self,goal:tuple[float,float,float]):
        self.goal_pos = goal

    def generate_safe_map(self, start_pos, goal_pos, buffer_radius=4.0):
        """
        Generates obstacles while ensuring a continuous clearance zone.
        """
        self.update_goal(goal_pos)

        safe_start = Point(start_pos[0], start_pos[1]).buffer(buffer_radius)
        safe_goal = Point(goal_pos[0], goal_pos[1]).buffer(buffer_radius)
        
        final_obstacles = []
        cell_size = 5

        candidate_coordinates = self._fill_map()
        print(candidate_coordinates)
        # Logic to pick random row/cols
        for row, col in candidate_coordinates:
            # Create the physical box for this obstacle
            obs_box = box(row * cell_size, col * cell_size, 
                        (row + 1) * cell_size, (col + 1) * cell_size)
            
            # CONTINUOUS CHECK:
            # If the box overlaps the 3m circle around start or goal, skip it.
            if obs_box.intersects(safe_start) or obs_box.intersects(safe_goal):
                continue
                
            final_obstacles.append((row, col))
        
        self.obstacle_coordinate_dict = dict.fromkeys(final_obstacles, Status.INTACT)
    
    def check_valid_cell(self, coordinate):
        """
        This will be used to check if the hero has access to the square

        This is intended be a safety check to ensure smooth motion
        """
        row, col = coordinate
        # Ensure we stay within the discrete grid bounds (0-11 for a 12x12)
        if not (0 <= row < self.grid_num and 0 <= col < self.grid_num):
            return False
        if (row, col) in self.obstacle_coordinate_dict.keys():
            return False
        return True


    def set_status_on_obstacles(self,coordinate:tuple[float,float],status:Status):
        obstacles_to_change_status = self.find_neighbor_obstacles(coordinate=coordinate)
        self._change_obstacle_status(obstacles_to_change_status,status)
        if status is Status.BURNING:
            for obstacle in obstacles_to_change_status:
                pass
                # self.update_obstacle_time[obstacle]

    def find_neighbor_obstacles(self,coordinate:tuple[float,float]):
        DIRECTIONS = [(1,0), (1,1),(0,1),(0,-1),(-1,-1),(1,-1),(-1,1),(-1,0)]
        all_connected_obstacles = []
        queue = Queue()
        queue.put(coordinate)
        while not queue.empty:
            currCoord = queue.get()
            for direction in DIRECTIONS:
                x,y = currCoord
                dx,dy = direction
                new_coord = (x+dx,y+dy)
                if new_coord in self.obstacle_coordinate_dict.keys():
                    all_connected_obstacles.append(new_coord)
                    queue.put(new_coord)
        
        return all_connected_obstacles


    def _append_new_obstacle(self, coordinate):
        self.obstacle_coordinate_dict[coordinate] = Status.INTACT
        # self.renderer.color_cell(coordinate)

    def _change_obstacle_status(self,coordinateList: list[tuple], status:Status):
        for coordinate in coordinateList:
            self.obstacle_coordinate_dict[coordinate] = status 

    def _delete_obstacle(self,coordinate):
        del self.obstacle_coordinate_dict[coordinate]

    # this function generates a random number associated with the shapes above
    def generate_random_tetromino(self):
        """This function generates a random number between 1 - 4 that is associated to a shape"""
        shape = random.choice([1, 2, 3, 4])
        return shape

    def generate_random_coord(self):
        """This function creates a random coordinate within the grid"""
        # 1. Create a list of all 16,384 possible (row, col) pairs
        all_coords = [
            (row, column)
            for row in range(self.grid_num)
            for column in range(self.grid_num)
        ]

        # 2. Pick unique pairs automatically
        sample = random.sample(all_coords, 1)
        return sample[0]

    def find_open_square(self):
        """This function uses a random coordinate and shape to determine if they would fit into the obstacle board's boundaries"""
        new_coordinate = self.generate_random_coord()
        if self.check_cell_occupied(new_coordinate):
            return self.find_open_square()
        else:
            return new_coordinate

    def check_cell_occupied(self, new_coordinate):
        if new_coordinate in self.obstacle_coordinate_dict.keys() or new_coordinate in [(0, 0),(1,0),(0,1),(1,1)]:
            return True
        if self.goal_pos:
            # Check if this grid cell contains the goal
            goal_grid = (
                int(self.goal_pos[0] / self.cell_size),
                int(self.goal_pos[1] / self.cell_size),
            )
            if new_coordinate == goal_grid:
                return True
        return False  # Ensure we return False if free

    def _generate_goal(self):
        """Generates a goal in a free cell and converts to world meters"""
        # 1. Find a random grid coordinate that isn't an obstacle
        all_coords = [
            (r, c) for r in range(self.grid_num) for c in range(self.grid_num)
        ]
        free_coords = [c for c in all_coords if c not in self.obstacle_coordinate_dict.keys()]

        if not free_coords:
            self.goal_pos = (
                self.grid_num * self.cell_size / 2,
                self.grid_num * self.cell_size / 2,
            )
            return

        target_cell = random.choice(free_coords)

        # 2. Convert grid index to real-world meters
        # Center of cell (row, col) is (row * 3 + 1.5, col * 3 + 1.5)
        self.goal_pos = (
            (target_cell[0] * self.cell_size) + (self.cell_size / 2),
            (target_cell[1] * self.cell_size) + (self.cell_size / 2),
        )

    def check_on_grid(self, coord):
        return 0 < coord[0] < self.grid_num and 0 < coord[1] < self.grid_num

    def generate_field_obstacle(self, shape, attempts=0):
        if attempts > 100:  # Reduced for smaller grids
            self.is_map_full = True
            return None

        # Pick a random starting point for the tetromino
        x, y = random.randint(0, self.grid_num - 1), random.randint(
            0, self.grid_num - 1
        )

        # Logic for shapes (using grid indices)
        # We replace the hardcoded '128' with self.grid_num
        potential_coords = []

        if shape == 1:  # Three Tall
            potential_coords = [(x, y), (x, y - 1), (x, y + 1)]
        elif shape == 2:  # L-Shape
            potential_coords = [(x, y), (x - 1, y - 1), (x, y - 1), (x, y + 1)]
        elif shape == 3:  # Z-Shape
            potential_coords = [(x, y), (x - 1, y - 1), (x - 1, y), (x, y + 1)]
        elif shape == 4:  # T-Shape
            potential_coords = [(x, y), (x, y - 1), (x, y + 1), (x - 1, y)]

        # Validate all pieces of the shape fit and are not overlapping
        valid = True
        for pc in potential_coords:
            if not (0 <= pc[0] < self.grid_num and 0 <= pc[1] < self.grid_num):
                valid = False
                break
            if self.check_cell_occupied(pc):
                valid = False
                break

        if valid:
            return potential_coords
        else:
            return self.generate_field_obstacle(shape, attempts + 1)

    

    def _fill_map(self):
        obstacle_list = []
        while (
            not self.is_map_full
            and len(obstacle_list)
            < self.grid_num * self.grid_num * self.fill_percent
        ):
            obstacles = (self.generate_field_obstacle(self.generate_random_tetromino()))
            if obstacles:
                obstacle_list.extend(obstacles)

        return obstacle_list
           


